name: ブランチ作成とforce push

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  create-branch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト(全ブランチ)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: make run
        run: make run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
